<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Thêm mới danh mục
        </h1>
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="box">
            <div class="box-body">
                <form action="/?action=createCategory" method="POST" class="form-inline" role="form">
                    <div class="form-group">
                        <input class="form-control" name="name" placeholder="Tên danh mục..">
                    </div>
                    <div class="form-group">
                        <div class="radio">
                            <label>
                                <input type="radio" name="status"  value="1" checked>
                                Hiển thị
                            </label>
                            <label>
                                <input type="radio" name="status"  value="0">
                                Ẩn
                            </label>
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary">Thêm</button>
                </form>
            </div>
        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>
