<?php
include '../config/connect.php';

?>

<form action="/?action=createProduct" method="POST" enctype="multipart/form-data">
    <div class="form-group">
        <label for="">Tên sản phẩm</label>
        <input class="form-control" name="name" placeholder="Tên sản phẩmc..">
    </div>
    <div class="form-group">
        <label for="">Ảnh đại diện</label>
        <input type="file" name="image" >
    </div>
    <div class="form-group">
        <label for="">Các ảnh khác</label>
        <input type="file" name="img[]"  multiple >
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <?php
                $cats = mysqli_query($conn,"SELECT * FROM category");

                ?>
                <label for="">Danh mục</label>
                <select name="category_id" class="form-control" required="required">
                    <option value="">Chọn danh mục</option>
                    <?php foreach($cats as $c) : ?>
                        <option value="<?php echo $c['id'] ?>"><?php echo $c['name'] ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="">Giá</label>
                <input class="form-control" name="price" placeholder="Giá..">
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="">Giá khuyến mãi</label>
                <input class="form-control" name="sale_price" placeholder="Giá khuyến mãi..">
            </div>
        </div>
    </div>
    </div>
    <div class="form-group">
        <label for="">Mô tả</label>
        <textarea name="description" class="form-control" rows="3" placeholder="Nhập nội dung mô tả"></textarea>
    </div>
    <div class="form-group">
        <label for="">Note</label>
        <select name="note" class="form-control">
            <option value="0">Ghi chú thêm</option>
            <option value="new">Sản phẩm new</option>
            <option value="sale">Sản phẩm có khuyến mãi</option>
            <option value="trends">Sản phầm Trends</option>
            <option value="adv">Sản phầm quảng cáo</option>
            <option value="best">Sản phầm best sale</option>
        </select>
    </div>
    <div class="form-group">
        <label for="">Trạng thái</label>
        <div class="radio">
            <label>
                <input type="radio" name="status"  value="1" checked>
                Hiển thị
            </label>
            <label>
                <input type="radio" name="status"  value="0">
                Ẩn
            </label>
        </div>
    </div>

    <button type="submit" class="btn btn-primary">Thêm</button>
</form>
