<?php
include '../config/connect.php';

?>

<form action="/?action=createUser" method="POST" role="form" enctype="multipart/form-data">
    <div class="form-group">
        <label for="">Fullname</label>
        <input type="text" name="name" class="form-control" id="" placeholder="Nhập họ tên...">
    </div>
    <div class="form-group">
        <label for="">Username</label>
        <input type="text" name="username" class="form-control" id="" placeholder="hoangtrung9937">
    </div>
    <div class="form-group">
        <label for="">Email</label>
        <input type="email" name="email" class="form-control" id="" placeholder="phamhaianh037@gmail.com">
    </div>
    <div class="form-group">
        <label for="">Phone</label>
        <input type="text" name="phone" class="form-control" id="" placeholder="0988974952">
    </div>
    <div class="form-group">
        <label for="">Birhday</label>
        <input type="date" name="birthday" class="form-control" id="" >
    </div>
    <div class="form-group">
        <label for="">Address</label>
        <input type="text" name="address" class="form-control" id="" >
    </div>
    <div class="form-group">
        <label for="">Avatar</label>
        <input type="file" name="image" class="form-control" id="" >
    </div>
    <div class="form-group">
        <label for="">Password</label>
        <input type="password" name="password" class="form-control" id="" placeholder="">
    </div>
    <div class="form-group">
        <label for="">Confirm-Password</label>
        <input type="password" name="confirm_password" class="form-control" id="" placeholder="">
    </div>
    <button type="submit" class="btn btn-primary">Thêm mới</button>
</form>
