
    <?php
    include '../config/connect.php';

    $sql_total=mysqli_query($conn,"SELECT id FROM users WHERE group_name='customer'");
    $total = mysqli_num_rows($sql_total);
    $order_total=mysqli_query($conn,"SELECT id FROM orders WHERE status=0");
    $od_total = mysqli_num_rows($order_total);
    $product_total=mysqli_query($conn,"SELECT id FROM product");
    $p_total=mysqli_num_rows($product_total);
    //Tính tổng doanh thu

    $sql_m="SELECT SUM(dt.price*dt.quantity) AS 'total' FROM order_detail dt ";
    $orders=mysqli_query($conn,$sql_m);
    $od=mysqli_fetch_assoc($orders);




    ?>

<div class="container">
    <div class="row">
        <div class="col-md-12 page-header">
            <div class="page-pretitle">Overview</div>
            <h2 class="page-title">Dashboard</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 col-md-6 col-lg-3">
            <div class="card">
                <div class="content">
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="icon-big text-center">
                                <i class="teal fas fa-shopping-cart"></i>
                            </div>
                        </div>
                        <div class="col-sm-8">
                            <div class="detail">
                                <p class="detail-subtitle">Số đơn hàng</p>
                                <span class="number"> <?= $od_total ?></span>
                            </div>
                        </div>
                    </div>
                    <div class="footer">
                        <hr />
                        <div class="stats">
                            <i class="fas fa-arrow-right"></i> Xem chi tiết
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-6 col-lg-3">
            <div class="card">
                <div class="content">
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="icon-big text-center">
                                <i class="olive fas fa-money-bill-alt"></i>
                            </div>
                        </div>
                        <div class="col-sm-8">
                            <div class="detail">
                                <p class="detail-subtitle">Doanh thu</p>
                                <h3>$<?php echo $od['total']; ?></h3>
                            </div>
                        </div>
                    </div>
                    <div class="footer">
                        <hr />
                        <div class="stats">
                            <i class="fas fa-arrow-right"></i> Xem chi tiết
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-6 col-lg-3">
            <div class="card">
                <div class="content">
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="icon-big text-center">
                                <i class="orange fas fa-envelope"></i>
                            </div>
                        </div>
                        <div class="col-sm-8">
                            <div class="detail">
                                <p class="detail-subtitle">Khách hàng</p>
                                <span class="number"><?= $total ?></span>
                            </div>
                        </div>
                    </div>
                    <div class="footer">
                        <hr />
                        <div class="stats">
                            <i class="fas fa-envelope-open-text"></i> For this week
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

