<?php
        $is_mini_mode = true;
        $escapeHtml = 'htmlspecialchars';
        $pro = isset($variables) ? $variables : [];
?>
<div class="single_product">
    <div class="container">
        <div class="row">
            <!-- Selected Image -->
            <div class="col-lg-5 order-lg-2 order-1">
                <div class="image_selected"><img src="./image/<?php echo $pro['image']; ?>" alt=""></div>
            </div>
            <!-- Description -->
            <div class="col-lg-5 order-3">
                <div class="product_description">
<!--                    <div class="product_category">--><?php //echo $pro['cat_name']; ?><!--</div>-->
                    <div class="product_name"><?php echo $pro['name']; ?></div>
                    <!-- <div class="rating_r rating_r_4 product_rating"><i></i><i></i><i></i><i></i><i></i></div> -->
                    <div class="product_text"><p><?php echo $pro['description']; ?></p></div>
                    <div class="order_info d-flex flex-row">
                        <div >
                            <div class="clearfix" style="z-index: 1000;">
                                <!-- Product Quantity -->
                                <div style="position: relative" class="product_quantity clearfix">
                                    <span>Quantity: </span>
                                    <input id="quantity_input" type="text" pattern="[1-10000]*" value="1" name="quantity">
                                    <input type="hidden" name="id" value="<?php echo $pro['id']; ?>">
                                    <div class="quantity_buttons">
                                        <div id="quantity_inc_button" class="quantity_inc quantity_control"><i class="fas fa-chevron-up"></i></div>
                                        <div id="quantity_dec_button" class="quantity_dec quantity_control"><i class="fas fa-chevron-down"></i></div>
                                    </div>
                                </div>
                            </div>
                            <div class="product_price"><?php if (empty($pro['sale_price'])): ?>
                                    <span>Price : </span>$<?php echo $pro['price'] ?>
                                <?php else: ?>
                                    <span>Price : </span>$<?php echo $pro['sale_price'] ; ?>
                                <?php endif ?></div>
                            <div class="button_container">
                                <a href="?action=cart&&quantity=1&&id=<?= $pro['id'] ?>">Add to Cart</a>
                                <div class="product_fav"><i class="fas fa-heart"></i></div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
?>
