<div class="login-wrap">
    <div class="login-html">
        <input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">Đăng nhập</label>
        <input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab">Đăng kí</label>
        <div class="login-form">
            <form class="sign-in-htm" action="/?action=loginsubmitted"  onsubmit="return validate()" method="post">
                <div class="group">
                    <label for="user-name-signin" class="label">Tên đăng nhập</label>
                    <input tyle="email" name="email"  type="text" class="input">
                </div>
                <div class="group">
                    <label for="pass-type-signin" class="label">Mật khẩu</label>
                    <input  name="password"  type="password" class="input" data-type="password">
                </div>
                <div class="group">
                    <input id="check" type="checkbox" class="check" checked>
                    <label for="check"><span class="icon"></span> Nhớ tài khoản</label>
                </div>
                <div class="group">
                    <input type="submit" class="button" value="Đăng nhập">
                </div>
                <div class="hr"></div>
                <div class="foot-lnk">
                    <a href="#forgot">Quên mật khẩu?</a>
                </div>
            </form>
            <form class="sign-up-htm" action="/?action=register" method="post">
                <div class="group">
                    <label for="username" class="label">Tên hiển thị</label>
                    <input id="name" name="name" type="text" class="input">
                </div>
                <div class="group">
                    <label for="username" class="label">Tên đăng nhập</label>
                    <input id="username" name="username" type="text" class="input">
                </div>
                <div class="group">
                    <label for="password" class="label">Mật khẩu</label>
                    <input name="password" type="password"  class="input" data-type="password">
                </div>
                <div class="group">
                    <label for="email" class="label">Địa chỉ Email</label>
                    <input name="email" type="email" class="input">
                </div>
                <div class="group">
                    <label for="phone" class="label">Số điện thoại</label>
                    <input id="phone"  name="phone" type="text" class="input">
                </div>
                <div class="group">
                    <label for="address" class="label">Địa chỉ</label>
                    <input name="address" type="text" class="input">
                </div>

                <div class="group">
                    <input type="submit" class="button" value="Đăng kí" >
                </div>
                <div class="hr"></div>
                <div class="foot-lnk">
                    <a for="tab-1">Đã có tài khoản?</a>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    function validate() {
        var result = "";
        result += validateEmail();
        result += validatePassword();

        if (result == "") return true;

        alert("Validation Result:\n\n" + result);
        return false;
    }


    function validatePassword() {
        var password = valueOf("password");

        if (password.length <= 3)
            return "Mật khẩu tối thiểu 3 kí tự\n";

        return "";
    }

    function checkEmail(email) {
        const re = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
        return re.test(email);
    }

    function validateEmail() {
        var email = valueOf("email");


        if (!checkEmail(email))
            return "Email không đúng định dạng\n";

        return "";
    }

    function valueOf(name) {
        return document.getElementsByName(name)[0].value;
    }

</script>
