<!DOCTYPE html>
<?php
include '../config/connect.php';
include '../config/cart.php';
?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Dan shop</title>


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="./css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">
    <link href="./css/bootstrap-theme.min.css" media="screen" rel="stylesheet" type="text/css">
    <link href="./css/style.css" media="screen" rel="stylesheet" type="text/css">
    <link href="./css/main_style.css" media="screen" rel="stylesheet" type="text/css">
    <link href="./css/bootstrap.css" media="screen" rel="stylesheet" type="text/css">
    <link
        href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css"
        rel="stylesheet"
    />
    <link href="./img/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon">
    <script type="text/javascript" src="/js/jquery-2.2.4.min.js"></script>
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>

    <script src="https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=tzzh9mce5uxzm7y4cnx1062zf4p6gkf6ggg9jgvf61dnv98w"></script>
    <script src="https://cdn.tiny.cloud/1/tzzh9mce5uxzm7y4cnx1062zf4p6gkf6ggg9jgvf61dnv98w/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script>tinymce.init({ selector:'textarea' });</script>




</head>
<body>

<header class="header">
    <div class="header__background">
        <div class="header__img">
            <img class="banner_image" src="./image/banner_background.jpg" alt="bg" />
        </div>
    </div>

    <nav class="nav bd-grid">
        <a href="#" class="nav__logo">
            <img src="./image/logoicon.png" alt="#" />
        </a>
        <div class="nav__box" id="nav-menu">
            <ul class="nav__list">
                <li class="nav__item">
                    <a href="#" class="nav__link">Home</a>
                </li>
                <li class="nav__item">
                    <a href="#" class="nav__link">Blog</a>
                </li>
                <li class="nav__item">
                    <a href="#" class="nav__link">About</a>
                </li>
                <li class="nav__item">
                    <a href="#" class="nav__link">Contact us</a>
                </li>
            </ul>

            <div class="row">

                <div class="nav__button">
                    <a href="#" class="nav__button-signup">Sign up</a>
                    <a href="#" class="nav__button-signin">Sign in</a>
                </div>
            </div>


        </div>
        <div class="nav__toggle" id="nav-toggle">
            <i class="bx bx-menu"></i>
        </div>
    </nav>

    <div class="header__information">
        <div class="header__title">
                <?php
                $pro=mysqli_query($conn,"SELECT * FROM product WHERE image like 'banner_product%'");
                $pr=mysqli_fetch_assoc($pro);
                ?>
                <div class="banner_product_image"><img src="./image/<?= $pr['image'] ?>" alt=""></div>
                <div class="header__description">
                    <div class="banner_content">
                        <h1 class="banner_text">new era of smartphones</h1>
                        <div class="banner_price"><span>$ <?= $pr['price'] ?></span>$<?= $pr['sale_price'] ?></div>
                        <div class="banner_product_name"><?= $pr['name'] ?></div>
                        <div class="button banner_button"><a href="process-cart.php?id=<?= $pr['id'] ?>">Shop Now</a></div>
                    </div>
                </div>
        </div>

<!--        <div class="header__title">-->
<!--            <h2>Find Yourself Outside.</h2>-->
<!--        </div>-->
<!--        <div class="header__description">-->
<!--            Book unique camping experiences on over 300,000 campsites, cabins, RV-->
<!--            parks, public parks and more.-->
<!--        </div>-->
<!--        <a href="#" class="header__button"> Discover </a>-->
    </div>
</header>

<main class="main bd-grid">
    <section class="service">
        <div class="service__item">
            <div class="header_main">
                <div class="container">
                    <div class="row">
                        <!-- Logo -->


                        <!-- Search -->
                        <div class="col-lg-8 col-12 text-right">
                            <div class="header_search">
                                <div class="header_search_content">
                                    <div class="header_search_form_container">
                                        <form action="search.php" class="header_search_form clearfix" method="GET">
                                            <input type="search" required="required" class="header_search_input" placeholder="Search for products..." name="search">
                                            <div class="custom_dropdown">
                                                <div class="custom_dropdown_list">
                                                    <span class="custom_dropdown_placeholder clc">All Categories</span>
                                                    <i class="fas fa-chevron-down"></i>
                                                    <ul class="custom_list clc">
                                                        <li><a class="clc" href="#">All Categories</a></li>
                                                        <li><a class="clc" href="#">Computers</a></li>
                                                        <li><a class="clc" href="#">Laptops</a></li>
                                                        <li><a class="clc" href="#">Cameras</a></li>
                                                        <li><a class="clc" href="#">Hardware</a></li>
                                                        <li><a class="clc" href="#">Smartphones</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                            <button type="submit" class="header_search_button trans_300"><img src="./image/search.png" alt=""></button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-2 col-sm-3 col-3">
                            <div class="logo_container">
                               <div class="cart">
                                    <div class="cart_container">
                                        <div class="cart_icon">
                                            <img src="./image/cart.png" alt="">
                                            <div class="cart_count"><span><?php echo tong_so_luong(); ?></span></div>
                                        </div>
                                        <div class="cart_content">
                                            <div class="cart_text"><a href="cart.php">Cart</a></div>
                                            <div class="cart_price">$<?php echo tong_tien(); ?></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="wrapper">

        <?= $this->content; ?>


    </section>

    <section class="subscribe">
        <div class="subscribe__bg">
            <img src="./image/mask.png" alt="img" />
        </div>
        <div class="subscribe__img">
            <img src="./image/homeicon.png" alt="homeicon" />
        </div>
        <form class="subscribe__form">
            <div class="subscribe__title">
                <h2>Let's Stay in Touch</h2>
            </div>
            <div class="subscribe__sub-title">
                <p>
                    Get travel planning ideas, helpful tips, and stories from our
                    visitors delivered right to your inbox.
                </p>
            </div>
            <div class="subscribe__input">
                <div class="subscribe__box-input">
                    <i class="bx bx-mail-send"></i>
                    <input type="text" placeholder="Email Address" />
                </div>
                <button type="submit" class="subscribe__send">
                    <i class="bx bxl-telegram"></i>
                </button>
            </div>
        </form>
    </section>
</main>

<!--<div class="container">-->
<!--    <div class="row">-->
<!--        <div class="col-md-12">-->
<!--            <nav class="navbar navbar-default">-->
<!--                <div class="container-fluid">-->
<!---->
<!--                    <ul class="nav navbar-nav">-->
<!---->
<!--                        --><?php
//                        if ($_SERVER['REQUEST_URI'] == "/")
//                            echo "<li class='active'><a href='#'>Home</a></li>";
//                        else
//                            echo "<li><a href='/'>Home</a></li>";
//
//                        if (!isset($_SESSION['adminid']) OR !$_SESSION['adminid'])
//                        {
//                            if ($_SERVER['REQUEST_URI'] == "/login")
//                                echo "<li class='active'><a href='#'>Login</a></li>";
//                            else
//                                echo "<li><a href='/login'>Login</a></li>";
//                        }
//
//
//
//                        if (isset($_SESSION['adminid']) AND $_SESSION['adminid']>0)
//                        {
//                            if ($_SERVER['REQUEST_URI'] == "/?action=addpost")
//                                echo "<li class='active'><a href='#'>Add entry</a></li>";
//                            else
//                                echo "<li><a href='/?action=addpost'>Add entry</a></li>";
//
//
//                            echo "<li><a href='/logout'>Logout</a></li>";
//                        }
//
//
//                        if ($_SERVER['REQUEST_URI'] == "/about")
//                            echo "<li class='active'><a href='#'>Contacts</a></li>";
//                        else
//                            echo "<li><a href='/about'>Contacts</a></li>";
//                        ?>
<!--                    </ul>-->
<!--                </div>-->
<!--            </nav>-->
<!---->
<!--        </div>-->
<!--    </div>-->
<!--    <div class="row">-->
<!--        <div class="col-md-12">-->
<!--            <!-- Breadcrumbs -->-->
<!--            --><?php ///* echo $this->pageBreadcrumbs()->render(); */ ?>
<!--        </div>-->
<!--    </div>-->
<!--    <div class="row">-->
<!--        <div class="col-md-12">-->
<!--            <!-- Page content placeholder -->-->
<!--            --><?//= $this->content; ?>
<!--        </div>-->
<!--    </div>-->
    <hr>
    <footer>
        <p>&copy; 2020 by Eugen Kaurov. All rights reserved. <a href="/about">Imprint (contacts)</a></p>
    </footer>
<!--</div>-->
<?php /* = $this->inlineScript() */ ?>
<script src="./js/main.js"></script>
</body>
</html>
