<!DOCTYPE html>
<?php
ob_start();
include '../config/connect.php';
include_once '../config/cart.php';
$id = null;
if(isset($_GET['id'])){
    $id = $_GET['id'];
}
?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Dan shop</title>


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="./css/bs.css" media="screen" rel="stylesheet" type="text/css">
    <link href="./css/style.css" media="screen" rel="stylesheet" type="text/css">
    <link href="./css/main_style.css" media="screen" rel="stylesheet" type="text/css">
    <link
        href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css"
        rel="stylesheet"
    />
    <link href="./fontawesome-free-5.0.1/css/fontawesome-all.css" rel="stylesheet" type="text/css">

</head>
<body>

<?php include 'header.php'; ?>

<main class="bd-grid">
    <section class="service">
        <div class="service__item">
            <div class="header_main">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-7 col-12 text-right">
                            <div class="header_search">
                                <div class="header_search_content">
                                    <div class="header_search_form_container">
                                        <form action="/?action=products" class="header_search_form clearfix" method="post">
                                            <input type="hidden"  name="id" value="<?= $id?>">
                                            <input type="search" required="required" class="header_search_input" placeholder="Tìm kiếm sản phẩm..." name="name">
                                            <button type="submit" class="header_search_button trans_300"><img src="./image/search.png" alt=""></button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-9 order-lg-3 order-2 text-lg-left text-right">
                            <div style="display: flex; flex-direction: row; align-items: center; justify-content: end" class="wishlist_cart">
                                <div style="display: flex; flex-direction: row; align-items: center; justify-content: end" class="wishlist">
                                    <div class="wishlist_icon"><img  src="./image/heart.png" alt=""></div>
                                    <div class="wishlist_content">
                                        <div class="wishlist_text"><a href="#">Wishlist</a></div>
                                        <div class="wishlist_count">115</div>
                                    </div>
                                </div>

                                <!-- Cart -->
                                <div class="cart">
                                    <a href="?action=cart">
                                        <div style="display: flex; flex-direction: row; align-items: center; justify-content: end">
                                            <div style="position: relative;" class="cart_icon">
                                                <img src="./image/cart.png" alt="">
                                                <div class="cart_count"><span><?php echo tong_so_luong(); ?></span></div>
                                            </div>
                                            <div class="cart_content">
                                                <div class="cart_text"><a>Cart</a></div>
                                                <div class="cart_price">$<?php echo tong_tien(); ?></div>
                                            </div>
                                        </div>
                                    </a>

                                </div>
                            </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="wrapper">

        <?= $this->content; ?>


    </section>

</main> -->

<?php include 'footer.php'; ?>



</body>
</html>
