<!DOCTYPE html>
<?php
ob_start();
include '../config/connect.php';
include_once '../config/cart.php';
$id = null;
if(isset($_GET['id'])){
    $id = $_GET['id'];
}
?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Dan shop</title>


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
<!--    <link href="./css/bootstrap4/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">-->
<!--    <link href="./css/bootstrap4/bootstrap-theme.min.css" media="screen" rel="stylesheet" type="text/css">-->
    <link href="./css/bootstrap.css" media="screen" rel="stylesheet" type="text/css">
    <link href="./css/style.css" media="screen" rel="stylesheet" type="text/css">
    <link href="./css/main_style.css" media="screen" rel="stylesheet" type="text/css">
    <link
        href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css"
        rel="stylesheet"
    />
    <link href="./fontawesome-free-5.0.1/css/fontawesome-all.css" rel="stylesheet" type="text/css">

    <link href="./img/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon">
    <script type="text/javascript" src="./js/jquery-2.2.4.min.js"></script>
    <script type="text/javascript" src="./js/bootstrap.min.js"></script>
    <script type="text/javascript" src="./js/main.js"></script>
    <script type="text/javascript" src="./js/product_custom.js"></script>
    <script src="https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=tzzh9mce5uxzm7y4cnx1062zf4p6gkf6ggg9jgvf61dnv98w"></script>
    <script src="https://cdn.tiny.cloud/1/tzzh9mce5uxzm7y4cnx1062zf4p6gkf6ggg9jgvf61dnv98w/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script>tinymce.init({ selector:'textarea' });</script>

</head>
<body>

<header class="header">
    <div class="header__background">
        <div class="header__img">
            <img class="banner_image" src="./image/banner_background.jpg" alt="bg" />
        </div>
    </div>

    <nav class="nav bd-grid">
        <a href="/" class="nav__logo">
            <img src="./image/logoicon.png" alt="#" />
        </a>
        <div class="nav__box" id="nav-menu">
            <ul class="nav__list">
                <li class="nav__item">
                    <a href="/" class="nav__link">Trang chủ</a>
                </li>
                <li class="nav__item">
                    <a href="#" class="nav__link">Bài viết</a>
                </li>
                <li class="nav__item">
                    <a href="#" class="nav__link">Thông tin</a>
                </li>
                <li class="nav__item">
                    <a href="#" class="nav__link">Liên hệ</a>
                </li>
            </ul>

            <div class="row">
                <div class="col">
                    <div class="main_nav_content" style="display: flex; flex-direction: row">
                <?php if(isset($_SESSION['login'])) : $u = $_SESSION['login']; ?>
                    <div class="top_bar_user">
                        <div class="dropdown">
                            <a href="#" class="dropbtn">
                                <div class="user_icon"><img src="./image/user.svg" alt=""></div>
                                <?php echo $u['name']; ?>
                                <b class="fas fa-angle-down"></b></a>
                            <div class="dropdown-content">
                                <a href="?action=logout"><i class="fas fa-sign-out-alt" style="margin: 10px;"></i>Log out</a>
                            </div>
                        </div>
                    </div>
                <?php else: ?>
                    <div class="top_bar_user">
                        <div class="nav__button">
                            <a href="/login" class="nav__button-signup" >Đăng ký</a>
                            <a href="/login" class="nav__button-signin">Đăng nhập</a>
                        </div>
                    </div>
                <?php endif; ?>

                    </div>
                    </div>
            </div>


        </div>
        <div class="nav__toggle" id="nav-toggle">
            <i class="bx bx-menu"></i>
        </div>
    </nav>

    <div class="header__information">
        <div class="header__title">
                <?php
                $pro=mysqli_query($conn,"SELECT * FROM product WHERE image like 'banner_product%'");
                $pr=mysqli_fetch_assoc($pro);
                ?>
                <div class="banner_product_image"><img src="./image/<?= $pr['image'] ?>" alt=""></div>
                <div class="header__description">
                    <div class="banner_content">
                        <h1 class="banner_text">Sản phẩm bán chạy</h1>
                        <div class="banner_price"><span>$ <?= $pr['price'] ?></span>$<?= $pr['sale_price'] ?></div>
                        <div class="banner_product_name"><?= $pr['name'] ?></div>
                        <div class="button banner_button"><a href="process-cart.php?id=<?= $pr['id'] ?>">Mua ngay</a></div>
                    </div>
                </div>

        </div>

<!--        <div class="header__title">-->
<!--            <h2>Find Yourself Outside.</h2>-->
<!--        </div>-->
<!--        <div class="header__description">-->
<!--            Book unique camping experiences on over 300,000 campsites, cabins, RV-->
<!--            parks, public parks and more.-->
<!--        </div>-->
<!--        <a href="#" class="header__button"> Discover </a>-->
    </div>
</header>

<main class="bd-grid">
    <section class="service">
        <div class="service__item">
            <div class="header_main">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-7 col-12 text-right">
                            <div class="header_search">
                                <div class="header_search_content">
                                    <div class="header_search_form_container">
                                        <form action="/?action=products" class="header_search_form clearfix" method="post">
                                            <input type="hidden"  name="id" value="<?= $id?>">
                                            <input type="search" required="required" class="header_search_input" placeholder="Tìm kiếm sản phẩm..." name="name">
                                            <button type="submit" class="header_search_button trans_300"><img src="./image/search.png" alt=""></button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-9 order-lg-3 order-2 text-lg-left text-right">
                            <div style="display: flex; flex-direction: row; align-items: center; justify-content: end" class="wishlist_cart">
                                <div style="display: flex; flex-direction: row; align-items: center; justify-content: end" class="wishlist">
                                    <div class="wishlist_icon"><img  src="./image/heart.png" alt=""></div>
                                    <div class="wishlist_content">
                                        <div class="wishlist_text"><a href="#">Wishlist</a></div>
                                        <div class="wishlist_count">115</div>
                                    </div>
                                </div>

                                <!-- Cart -->
                                <div class="cart">
                                    <a href="?action=cart">
                                        <div style="display: flex; flex-direction: row; align-items: center; justify-content: end">
                                            <div style="position: relative;" class="cart_icon">
                                                <img src="./image/cart.png" alt="">
                                                <div class="cart_count"><span><?php echo tong_so_luong(); ?></span></div>
                                            </div>
                                            <div class="cart_content">
                                                <div class="cart_text"><a>Cart</a></div>
                                                <div class="cart_price">$<?php echo tong_tien(); ?></div>
                                            </div>
                                        </div>
                                    </a>

                                </div>
                            </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="wrapper">

        <?= $this->content; ?>


    </section>

    <!-- <section class="subscribe">
        <div class="subscribe__bg">
            <img src="./image/mask.png" alt="img" />
        </div>
        <div class="subscribe__img">
            <img src="./image/homeicon.png" alt="homeicon" />
        </div>
        <form class="subscribe__form">
            <div class="subscribe__title">
                <h2>Let's Stay in Touch</h2>
            </div>
            <div class="subscribe__sub-title">
                <p>
                    Get travel planning ideas, helpful tips, and stories from our
                    visitors delivered right to your inbox.
                </p>
            </div>
            <div class="subscribe__input">
                <div class="subscribe__box-input">
                    <i class="bx bx-mail-send"></i>
                    <input type="text" placeholder="Email Address" />
                </div>
                <button type="submit" class="subscribe__send">
                    <i class="bx bxl-telegram"></i>
                </button>
            </div>
        </form>
    </section>
</main> -->

<!--<div class="container">-->
<!--    <div class="row">-->
<!--        <div class="col-md-12">-->
<!--            <nav class="navbar navbar-default">-->
<!--                <div class="container-fluid">-->
<!---->
<!--                    <ul class="nav navbar-nav">-->
<!---->
<!--                        --><?php
//                        if ($_SERVER['REQUEST_URI'] == "/")
//                            echo "<li class='active'><a href='#'>Home</a></li>";
//                        else
//                            echo "<li><a href='/'>Home</a></li>";
//
//                        if (!isset($_SESSION['adminid']) OR !$_SESSION['adminid'])
//                        {
//                            if ($_SERVER['REQUEST_URI'] == "/login")
//                                echo "<li class='active'><a href='#'>Login</a></li>";
//                            else
//                                echo "<li><a href='/login'>Login</a></li>";
//                        }
//
//
//
//                        if (isset($_SESSION['adminid']) AND $_SESSION['adminid']>0)
//                        {
//                            if ($_SERVER['REQUEST_URI'] == "/?action=addpost")
//                                echo "<li class='active'><a href='#'>Add entry</a></li>";
//                            else
//                                echo "<li><a href='/?action=addpost'>Add entry</a></li>";
//
//
//                            echo "<li><a href='/logout'>Logout</a></li>";
//                        }
//
//
//                        if ($_SERVER['REQUEST_URI'] == "/about")
//                            echo "<li class='active'><a href='#'>Contacts</a></li>";
//                        else
//                            echo "<li><a href='/about'>Contacts</a></li>";
//                        ?>
<!--                    </ul>-->
<!--                </div>-->
<!--            </nav>-->
<!---->
<!--        </div>-->
<!--    </div>-->
<!--    <div class="row">-->
<!--        <div class="col-md-12">-->
<!--            <!-- Breadcrumbs -->-->
<!--            --><?php ///* echo $this->pageBreadcrumbs()->render(); */ ?>
<!--        </div>-->
<!--    </div>-->
<!--    <div class="row">-->
<!--        <div class="col-md-12">-->
<!--            <!-- Page content placeholder -->-->
<!--            --><?//= $this->content; ?>
<!--        </div>-->
<!--    </div>-->
    <hr>
    <footer>
        <p>&copy; 2020 by Eugen Kaurov. All rights reserved. <a href="/about">Imprint (contacts)</a></p>
    </footer>
<!--</div>-->

<?php
/* = $this->inlineScript() */ ?>

</body>
</html>
