<!DOCTYPE html>
<?php
ob_start();
?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Đăng nhập</title>


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
<!--    <link href="./css/bootstrap4/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">-->
<!--    <link href="./css/bootstrap4/bootstrap-theme.min.css" media="screen" rel="stylesheet" type="text/css">-->
    <link href="./css/bootstrap.css" media="screen" rel="stylesheet" type="text/css">
    <link href="./css/style.css" media="screen" rel="stylesheet" type="text/css">
    <link href="./css/main_style.css" media="screen" rel="stylesheet" type="text/css">
</head>
<body>
<?= $this->content1; ?>

<!--</div>-->

    <?php
    /* = $this->inlineScript() */ ?>
<!--<script type="text/javascript" src="./js/jquery-2.2.4.min.js"></script>-->
<!--<script type="text/javascript" src="./js/bootstrap.min.js"></script>-->
</body>
</html>
